spring:
  servlet:
    context-path: /
    encoding: # 한글 입출력 설정
      charset: UTF-8
      enabled: true
      force: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
    properties:
      hibernate:
        format_sql: true
    # open-in-view: false

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017

    redis:
      host: 127.0.0.1
      port: 6379

client:
  url: "http://localhost:3000"

jwt:
  secret: EDhNNRGcsef693YrFrClvyeCIVDUleWTvC7N3sT0lREmULTM
  expiration-period-minutes: 1440 # 24 Hours
