name: deploy OCI

on:
  push:
    branches: ["main"]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
      APPLICATION: ${{ secrets.APPLICATION }}
      APPLICATION_TEST: ${{ secrets.APPLICATION_TEST }}
    
    steps:
      # repository code pull
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy application.yml
        run: |
          mkdir -p ./src/main/resources
          mkdir -p ./src/test/resources
          touch ./src/main/resources/application.yml
          echo "${{env.APPLICATION}}" > ./src/main/resources/application.yml
          touch ./src/test/resources/application.yml
          echo "${{env.APPLICATION_TEST}}" > ./src/test/resources/application.yml

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose        
      
      - name: Execute Gradle Build
        run: ./gradlew build