name: deploy OCI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
      APPLICATION: ${{ secrets.APPLICATION }}
    
    steps:
      # repository code pull
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{env.APPLICATION}}" > ./src/main/resources/application.yml          

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose        
      
      - name: Execute Gradle Build
        run: ./gradlew build
        
